[build]
  publish = "public"
  command = "npm run build"
[build.environment]
  NODE_VERSION = "18.18.2"
[[plugins]]
  package = "netlify-plugin-cloudinary"

  [plugins.inputs]
  deliveryType = "upload"
